In [52]:
import numpy as np
import pandas as pd

In [53]:
df = pd.read_csv("RecSys-Materials/ml-latest-small/ratings.csv")

In [54]:
 df.shape

(100004, 4)

In [55]:
df.head(50)

    userId  movieId  rating   timestamp
0        1       31     2.5  1260759144
1        1     1029     3.0  1260759179
2        1     1061     3.0  1260759182
3        1     1129     2.0  1260759185
4        1     1172     4.0  1260759205
5        1     1263     2.0  1260759151
6        1     1287     2.0  1260759187
7        1     1293     2.0  1260759148
8        1     1339     3.5  1260759125
9        1     1343     2.0  1260759131
10       1     1371     2.5  1260759135
11       1     1405     1.0  1260759203
12       1     1953     4.0  1260759191
13       1     2105     4.0  1260759139
14       1     2150     3.0  1260759194
15       1     2193     2.0  1260759198
16       1     2294     2.0  1260759108
17       1     2455     2.5  1260759113
18       1     2968     1.0  1260759200
19       1     3671     3.0  1260759117
20       2       10     4.0   835355493
21       2       17     5.0   835355681
22       2       39     5.0   835355604
23       2       47     4.0   835355552
24       2       50     4.0   835355586
25       2       52     3.0   835356031
26       2       62     3.0   835355749
27       2      110     4.0   835355532
28       2      144     3.0   835356016
29       2      150     5.0   835355395
30       2      153     4.0   835355441
31       2      161     3.0   835355493
32       2      165     3.0   835355441
33       2      168     3.0   835355710
34       2      185     3.0   835355511
35       2      186     3.0   835355664
36       2      208     3.0   835355511
37       2      222     5.0   835355840
38       2      223     1.0   835355749
39       2      225     3.0   835355552
40       2      235     3.0   835355664
41       2      248     3.0   835355896
42       2      253     4.0   835355511
43       2      261     4.0   835355681
44       2      265     5.0   835355697
45       2      266     5.0   835355586
46       2      272     3.0   835355767
47       2      273     4.0   835355779
48       2      292     3.0   835355492
49       2      296     4.0   835355395

In [56]:
al = pd.read_csv("RecSys-Materials/ml-latest-small/movies.csv")

In [57]:
al.shape

(9125, 3)

In [11]:
al.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [7]:
dt = pd.read_csv("RecSys-Materials/ml-latest-small/tags.csv")

In [28]:
dt.shape

(1296, 4)

In [51]:
dt.head()

   userId  movieId                      tag   timestamp
0      15      339  sandra 'boring' bullock  1138537770
1      15     1955                  dentist  1193435061
2      15     7478                 Cambodia  1170560997
3      15    32892                  Russian  1170626366
4      15    34162              forgettable  1141391765

In [9]:
dt.head()

   userId  movieId                      tag   timestamp
0      15      339  sandra 'boring' bullock  1138537770
1      15     1955                  dentist  1193435061
2      15     7478                 Cambodia  1170560997
3      15    32892                  Russian  1170626366
4      15    34162              forgettable  1141391765

In [48]:
data = pd.merge(df, al, how = 'left', on = ['movieId'])

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100004 entries, 0 to 100003
Data columns (total 6 columns):
userId       100004 non-null int64
movieId      100004 non-null int64
rating       100004 non-null float64
timestamp    100004 non-null int64
title        100004 non-null object
genres       100004 non-null object
dtypes: float64(1), int64(3), object(2)
memory usage: 5.3+ MB

In [29]:
data = pd.merge(data, dt, how = 'left', on = ['movieId'])

In [37]:
data.head(10)

,userId_x,movieId,rating,timestamp_x,title,genres,userId_y,tag,timestamp_y
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,212.0,emotional,1.253930e+09
3,1,1061,3.0,1260759182,Sleepers (1996),Thriller,212.0,revenge,1.253930e+09
4,1,1061,3.0,1260759182,Sleepers (1996),Thriller,212.0,true story,1.253930e+09
6,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,547.0,holes80s,1.342849e+09
20,1,2968,1.0,1260759200,Time Bandits (1981),Adventure|Comedy|Fantasy|Sci-Fi,77.0,Gilliam,1.163220e+09
21,1,2968,1.0,1260759200,Time Bandits (1981),Adventure|Comedy|Fantasy|Sci-Fi,77.0,Trilogy of the Imagination,1.163220e+09
22,1,3671,3.0,1260759117,Blazing Saddles (1974),Comedy|Western,547.0,holes70s,1.342849e+09
26,2,47,4.0,835355552,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,364.0,biblical,1.444535e+09
27,2,47,4.0,835355552,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,364.0,crime,1.444535e+09
28,2,47,4.0,835355552,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,364.0,dark,1.444535e+09

In [31]:
data.dropna(subset=['tag'], how = 'all', inplace=True)

In [35]:
data.head()

,userId_x,movieId,rating,timestamp_x,title,genres,userId_y,tag,timestamp_y
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,212.0,emotional,1.253930e+09
3,1,1061,3.0,1260759182,Sleepers (1996),Thriller,212.0,revenge,1.253930e+09
4,1,1061,3.0,1260759182,Sleepers (1996),Thriller,212.0,true story,1.253930e+09
6,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,547.0,holes80s,1.342849e+09
20,1,2968,1.0,1260759200,Time Bandits (1981),Adventure|Comedy|Fantasy|Sci-Fi,77.0,Gilliam,1.163220e+09

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63125 entries, 2 to 141013
Data columns (total 9 columns):
userId_x       63125 non-null int64
movieId        63125 non-null int64
rating         63125 non-null float64
timestamp_x    63125 non-null int64
title          63125 non-null object
genres         63125 non-null object
userId_y       63125 non-null float64
tag            63125 non-null object
timestamp_y    63125 non-null float64
dtypes: float64(3), int64(3), object(3)
memory usage: 4.8+ MB

In [41]:
data.drop_duplicates('movieId', inplace = True)

In [44]:
data.head(10)

,userId_x,movieId,rating,timestamp_x,title,genres,userId_y,tag,timestamp_y
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,212.0,emotional,1.253930e+09
6,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,547.0,holes80s,1.342849e+09
20,1,2968,1.0,1260759200,Time Bandits (1981),Adventure|Comedy|Fantasy|Sci-Fi,77.0,Gilliam,1.163220e+09
22,1,3671,3.0,1260759117,Blazing Saddles (1974),Comedy|Western,547.0,holes70s,1.342849e+09
26,2,47,4.0,835355552,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,364.0,biblical,1.444535e+09
36,2,50,4.0,835355586,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,364.0,thriller,1.444535e+09
41,2,150,5.0,835355395,Apollo 13 (1995),Adventure|Drama|IMAX,23.0,Ron Howard,1.148673e+09
43,2,153,4.0,835355441,Batman Forever (1995),Action|Adventure|Comedy|Crime,313.0,Ei muista,1.168879e+09
48,2,186,3.0,835355664,Nine Months (1995),Comedy|Romance,431.0,hugh grant,1.140455e+09
62,2,296,4.0,835355395,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,84.0,intense,1.429911e+09

### collobarative filtering

There is very useful and easy to use library, that you can use to realize recommender systems algorithms, **surpise**.

First of all lets talk about dataset type, loading a rating dataset can be done either from a file(e.g. a csv file) or from a pandas dataframe. Either way, you will need to define  a **Reader** object for Surprise to able to parse the file or the dataframe.

In [8]:
from surprise import SVD, Dataset
from surprise.model_selection import cross_validate
from surprise import BaselineOnly
from surprise import Dataset
from surprise import Reader

In [9]:
df.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [10]:
reader = Reader(rating_scale=(1,5))

In [11]:
reader

In [12]:
data = Dataset.load_from_df(df[['userId','movieId','rating']],reader)

In [13]:
data

In [14]:
algo = SVD()

In [15]:
cross_validate(algo,data,measures=['RMSE','MAE'],cv=3,verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 3 split(s).

                  Fold 1  Fold 2  Fold 3  Mean    Std
RMSE (testset)    0.8957  0.9101  0.9061  0.9040  0.0061
MAE (testset)     0.6891  0.7027  0.6988  0.6968  0.0057
Fit time          5.96    6.52    5.67    6.05    0.35
Test time         0.90    0.39    0.41    0.57    0.24

{'fit_time': (5.9636828899383545, 6.519441604614258, 5.671576023101807),
 'test_mae': array([0.68905856, 0.70265539, 0.69878585]),
 'test_rmse': array([0.89569783, 0.91007422, 0.90614375]),
 'test_time': (0.9009559154510498, 0.3943042755126953, 0.4067075252532959)}

if u dont use run full a full cross validation process, you can just use the train test split method.

In [16]:
from surprise import accuracy
from surprise.model_selection import train_test_split
from surprise.model_selection import KFold

In [17]:
trainset,testset = train_test_split(data,test_size=.25)

In [18]:
algo = SVD()
algo.fit(trainset)
predictions = algo.test(testset)
accuracy.rmse(predictions)

RMSE: 0.8964

0.8964333792647025

cross validation iterators

Here is an example where we use a classical K-fold cross-validation procedure with 3 splits:

In [19]:
kf = KFold(n_splits=3)
for trainset, testset in kf.split(data):
    algo.fit(trainset)
    predictions = algo.test(testset)
    accuracy.rmse(predictions,verbose=True)

RMSE: 0.9004
RMSE: 0.9019
RMSE: 0.9085

###  tune parameters with grid search

In [20]:
from surprise.model_selection import GridSearchCV

In [21]:
param_grid = {
    'n_epochs':[5,10],
    'lr_all':[0.002,0.005],
    'reg_all':[0.4,0.6]
}
gs = GridSearchCV(SVD,param_grid,measures=['rmse','mae'],cv=3)
gs.fit(data)

In [22]:
gs.best_score['rmse']

0.9139216490964825

In [23]:
gs.best_params

{'mae': {'lr_all': 0.005, 'n_epochs': 10, 'reg_all': 0.4},
 'rmse': {'lr_all': 0.005, 'n_epochs': 10, 'reg_all': 0.4}}

### There we are gonna to build recommender system with Surprise library, and will check some of the metrics, which will help us to the better data understanding

In [24]:
import os
import csv
import sys
import re
from surprise import Dataset
from surprise import Reader
from collections import defaultdict

In [27]:
class MovieLens:

    movieID_to_name = {}
    name_to_movieID = {}
    ratingsPath = "/home/norton/Desktop/ML/RecSys-Materials/ml-latest-small/ratings.csv"
    moviesPath   = "/home/norton/Desktop/ML/RecSys-Materials/ml-latest-small/movies.csv"

    def loadMovieLensLatestSmall(self):

        # Look for files relative to the directory we are running from
        os.chdir(os.path.dirname(sys.argv[0]))

        ratingsDataset = 0
        self.movieID_to_name = {}
        self.name_to_movieID = {}

        reader = Reader(line_format='user item rating timestamp', sep=',', skip_lines=1)

        ratingsDataset = Dataset.load_from_file(self.ratingsPath, reader=reader)

        with open(self.moviesPath, newline='', encoding='ISO-8859-1') as csvfile:
                movieReader = csv.reader(csvfile)
                next(movieReader)  #Skip header line
                for row in movieReader:
                    movieID = int(row[0])
                    movieName = row[1]
                    self.movieID_to_name[movieID] = movieName
                    self.name_to_movieID[movieName] = movieID

        return ratingsDataset

    def getUserRatings(self, user):
        userRatings = []
        hitUser = False
        with open(self.ratingsPath, newline='') as csvfile:
            ratingReader = csv.reader(csvfile)
            next(ratingReader)
            for row in ratingReader:
                userID = int(row[0])
                if (user == userID):
                    movieID = int(row[1])
                    rating = float(row[2])
                    userRatings.append((movieID, rating))
                    hitUser = True
                if (hitUser and (user != userID)):
                    break

        return userRatings

    def getPopularityRanks(self):
        ratings = defaultdict(int)
        rankings = defaultdict(int)
        with open(self.ratingsPath, newline='') as csvfile:
            ratingReader = csv.reader(csvfile)
            next(ratingReader)
            for row in ratingReader:
                movieID = int(row[1])
                ratings[movieID] += 1
        rank = 1
        for movieID, ratingCount in sorted(ratings.items(), key=lambda x: x[1], reverse=True):
            rankings[movieID] = rank
            rank += 1
        return rankings
    
    def getGenres(self):
        genres = defaultdict(list)
        genreIDs = {}
        maxGenreID = 0
        with open(self.moviesPath, newline='', encoding='ISO-8859-1') as csvfile:
            movieReader = csv.reader(csvfile)
            next(movieReader)  #Skip header line
            for row in movieReader:
                movieID = int(row[0])
                genreList = row[2].split('|')
                genreIDList = []
                for genre in genreList:
                    if genre in genreIDs:
                        genreID = genreIDs[genre]
                    else:
                        genreID = maxGenreID
                        genreIDs[genre] = genreID
                        maxGenreID += 1
                    genreIDList.append(genreID)
                genres[movieID] = genreIDList
        # Convert integer-encoded genre lists to bitfields that we can treat as vectors
        for (movieID, genreIDList) in genres.items():
            bitfield = [0] * maxGenreID
            for genreID in genreIDList:
                bitfield[genreID] = 1
            genres[movieID] = bitfield            
        
        return genres
    
    def getYears(self):
        p = re.compile(r"(?:\((\d{4})\))?\s*$")
        years = defaultdict(int)
        with open(self.moviesPath, newline='', encoding='ISO-8859-1') as csvfile:
            movieReader = csv.reader(csvfile)
            next(movieReader)
            for row in movieReader:
                movieID = int(row[0])
                title = row[1]
                m = p.search(title)
                year = m.group(1)
                if year:
                    years[movieID] = int(year)
        return years
    
    def getMiseEnScene(self):
        mes = defaultdict(list)
        with open("LLVisualFeatures13K_Log.csv", newline='') as csvfile:
            mesReader = csv.reader(csvfile)
            next(mesReader)
            for row in mesReader:
                movieID = int(row[0])
                avgShotLength = float(row[1])
                meanColorVariance = float(row[2])
                stddevColorVariance = float(row[3])
                meanMotion = float(row[4])
                stddevMotion = float(row[5])
                meanLightingKey = float(row[6])
                numShots = float(row[7])
                mes[movieID] = [avgShotLength, meanColorVariance, stddevColorVariance,
                   meanMotion, stddevMotion, meanLightingKey, numShots]
        return mes
    
    def getMovieName(self, movieID):
        if movieID in self.movieID_to_name:
            return self.movieID_to_name[movieID]
        else:
            return ""
        
    def getMovieID(self, movieName):
        if movieName in self.name_to_movieID:
            return self.name_to_movieID[movieName]
        else:
            return 0

In [28]:


def BuildAntiTestSetForUser(testSubject, trainset):
    fill = trainset.global_mean

    anti_testset = []
    
    u = trainset.to_inner_uid(str(testSubject))
    
    user_items = set([j for (j, _) in trainset.ur[u]])
    anti_testset += [(trainset.to_raw_uid(u), trainset.to_raw_iid(i), fill) for
                             i in trainset.all_items() if
                             i not in user_items]
    return anti_testset

# Pick an arbitrary test subject
testSubject = 85

ml = MovieLens()

print("Loading movie ratings...")
data = ml.loadMovieLensLatestSmall()

userRatings = ml.getUserRatings(testSubject)
loved = []
hated = []
for ratings in userRatings:
    if (float(ratings[1]) > 4.0):
        loved.append(ratings)
    if (float(ratings[1]) < 3.0):
        hated.append(ratings)

print("\nUser ", testSubject, " loved these movies:")
for ratings in loved:
    print(ml.getMovieName(ratings[0]))
print("\n...and didn't like these movies:")
for ratings in hated:
    print(ml.getMovieName(ratings[0]))

print("\nBuilding recommendation model...")
trainSet = data.build_full_trainset()

algo = SVD()
algo.fit(trainSet)

print("Computing recommendations...")
testSet = BuildAntiTestSetForUser(testSubject, trainSet)
predictions = algo.test(testSet)

recommendations = []

print ("\nWe recommend:")
for userID, movieID, actualRating, estimatedRating, _ in predictions:
    intMovieID = int(movieID)
    recommendations.append((intMovieID, estimatedRating))

recommendations.sort(key=lambda x: x[1], reverse=True)

for ratings in recommendations[:10]:
    print(ml.getMovieName(ratings[0]))

Loading movie ratings...

User  85  loved these movies:
Jumanji (1995)
GoldenEye (1995)
Braveheart (1995)
Jerky Boys, The (1995)
LÃ©on: The Professional (a.k.a. The Professional) (LÃ©on) (1994)
Pulp Fiction (1994)
Stargate (1994)
Shawshank Redemption, The (1994)
Star Trek: Generations (1994)
Clear and Present Danger (1994)
Speed (1994)
True Lies (1994)
Fugitive, The (1993)
Jurassic Park (1993)
Terminator 2: Judgment Day (1991)
Mission: Impossible (1996)
Rock, The (1996)

...and didn't like these movies:
Grumpier Old Men (1995)
Mortal Kombat (1995)
Postman, The (Postino, Il) (1994)
Casper (1995)
Lord of Illusions (1995)
Mighty Morphin Power Rangers: The Movie (1995)
Prophecy, The (1995)
Dolores Claiborne (1995)
Heavenly Creatures (1994)
Little Women (1994)
Miracle on 34th Street (1994)
Nell (1994)
Poison Ivy II (1996)
Tank Girl (1995)
While You Were Sleeping (1995)
Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale, A) (1994)
Naked Gun 33 1/3: The Final Insult (1994)
Richie Rich (1994)
Beverly Hills Cop III (1994)
Philadelphia (1993)
Schindler's List (1993)
Super Mario Bros. (1993)
Nightmare Before Christmas, The (1993)
Snow White and the Seven Dwarfs (1937)
Operation Dumbo Drop (1995)
Oliver & Company (1988)

Building recommendation model...
Computing recommendations...

We recommend:
Matrix, The (1999)
African Queen, The (1951)
12 Angry Men (1957)
Lord of the Rings: The Return of the King, The (2003)
Godfather: Part II, The (1974)
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)
Departed, The (2006)
Indiana Jones and the Last Crusade (1989)
Raging Bull (1980)
Dark Knight, The (2008)

In [29]:
import itertools
from surprise import accuracy
from collections import defaultdict

In [30]:
class RecommenderMetrics:
    # Mean absoulte error
    def MAE(predictions):
        return accuracy.mae(predictions, verbose=False)

    # root mean score error
    def RMSE(predictions):
        return accuracy.rmse(predictions, verbose=False)

    # just gives you topN recommendations per user, with ability to change threshold
    def GetTopN(predictions, n=10, minimumRating=4.0):
        topN = defaultdict(list)


        for userID, movieID, actualRating, estimatedRating, _ in predictions:
            if (estimatedRating >= minimumRating):
                topN[int(userID)].append((int(movieID), estimatedRating))

        for userID, ratings in topN.items():
            ratings.sort(key=lambda x: x[1], reverse=True)
            topN[int(userID)] = ratings[:n]

        return topN

    # gives you hit rate
    def HitRate(topNPredicted, leftOutPredictions):
        hits = 0
        total = 0

        # For each left-out rating
        for leftOut in leftOutPredictions:
            userID = leftOut[0]
            leftOutMovieID = leftOut[1]
            # Is it in the predicted top 10 for this user?
            hit = False
            for movieID, predictedRating in topNPredicted[int(userID)]:
                if (int(leftOutMovieID) == int(movieID)):
                    hit = True
                    break
            if (hit) :
                hits += 1

            total += 1

        # Compute overall precision
        return hits/total
    
    
    def CumulativeHitRate(topNPredicted, leftOutPredictions, ratingCutoff=0):
        hits = 0
        total = 0

        # For each left-out rating
        for userID, leftOutMovieID, actualRating, estimatedRating, _ in leftOutPredictions:
            # Only look at ability to recommend things the users actually liked...
            if (actualRating >= ratingCutoff):
                # Is it in the predicted top 10 for this user?
                hit = False
                for movieID, predictedRating in topNPredicted[int(userID)]:
                    if (int(leftOutMovieID) == movieID):
                        hit = True
                        break
                if (hit) :
                    hits += 1

                total += 1

        # Compute overall precision
        return hits/total

    def RatingHitRate(topNPredicted, leftOutPredictions):
        hits = defaultdict(float)
        total = defaultdict(float)

        # For each left-out rating
        for userID, leftOutMovieID, actualRating, estimatedRating, _ in leftOutPredictions:
            # Is it in the predicted top N for this user?
            hit = False
            for movieID, predictedRating in topNPredicted[int(userID)]:
                if (int(leftOutMovieID) == movieID):
                    hit = True
                    break
            if (hit) :
                hits[actualRating] += 1

            total[actualRating] += 1

        # Compute overall precision
        for rating in sorted(hits.keys()):
            print (rating, hits[rating] / total[rating])

    def AverageReciprocalHitRank(topNPredicted, leftOutPredictions):
        summation = 0
        total = 0
        # For each left-out rating
        for userID, leftOutMovieID, actualRating, estimatedRating, _ in leftOutPredictions:
            # Is it in the predicted top N for this user?
            hitRank = 0
            rank = 0
            for movieID, predictedRating in topNPredicted[int(userID)]:
                rank = rank + 1
                if (int(leftOutMovieID) == movieID):
                    hitRank = rank
                    break
            if (hitRank > 0) :
                summation += 1.0 / hitRank

            total += 1

        return summation / total

    # What percentage of users have at least one "good" recommendation
    def UserCoverage(topNPredicted, numUsers, ratingThreshold=0):
        hits = 0
        for userID in topNPredicted.keys():
            hit = False
            for movieID, predictedRating in topNPredicted[userID]:
                if (predictedRating >= ratingThreshold):
                    hit = True
                    break
            if (hit):
                hits += 1

        return hits / numUsers

    def Diversity(topNPredicted, simsAlgo):
        n = 0
        total = 0
        simsMatrix = simsAlgo.compute_similarities()
        for userID in topNPredicted.keys():
            pairs = itertools.combinations(topNPredicted[userID], 2)
            for pair in pairs:
                movie1 = pair[0][0]
                movie2 = pair[1][0]
                innerID1 = simsAlgo.trainset.to_inner_iid(str(movie1))
                innerID2 = simsAlgo.trainset.to_inner_iid(str(movie2))
                similarity = simsMatrix[innerID1][innerID2]
                total += similarity
                n += 1

        S = total / n
        return (1-S)

    def Novelty(topNPredicted, rankings):
        n = 0
        total = 0
        for userID in topNPredicted.keys():
            for rating in topNPredicted[userID]:
                movieID = rating[0]
                rank = rankings[movieID]
                total += rank
                n += 1
        return total / n

In [31]:
from surprise import SVD
from surprise import KNNBaseline
from surprise.model_selection import train_test_split
from surprise.model_selection import LeaveOneOut
#from RecommenderMetrics import RecommenderMetrics

In [ ]:
ml = MovieLens()

print("Loading movie ratings...")
data = ml.loadMovieLensLatestSmall()

print("\nComputing movie popularity ranks so we can measure novelty later...")
rankings = ml.getPopularityRanks()

print("\nComputing item similarities so we can measure diversity later...")
fullTrainSet = data.build_full_trainset()
sim_options = {'name': 'pearson_baseline', 'user_based': False}
simsAlgo = KNNBaseline(sim_options=sim_options)
simsAlgo.fit(fullTrainSet)

print("\nBuilding recommendation model...")
trainSet, testSet = train_test_split(data, test_size=.25, random_state=1)

algo = SVD(random_state=10)
algo.fit(trainSet)

print("\nComputing recommendations...")
predictions = algo.test(testSet)

print("\nEvaluating accuracy of model...")
print("RMSE: ", RecommenderMetrics.RMSE(predictions))
print("MAE: ", RecommenderMetrics.MAE(predictions))

print("\nEvaluating top-10 recommendations...")

# Set aside one rating per user for testing
LOOCV = LeaveOneOut(n_splits=1, random_state=1)

for trainSet, testSet in LOOCV.split(data):
    print("Computing recommendations with leave-one-out...")

    # Train model without left-out ratings
    algo.fit(trainSet)

    # Predicts ratings for left-out ratings only
    print("Predict ratings for left-out set...")
    leftOutPredictions = algo.test(testSet)

    # Build predictions for all ratings not in the training set
    print("Predict all missing ratings...")
    bigTestSet = trainSet.build_anti_testset()
    allPredictions = algo.test(bigTestSet)

    # Compute top 10 recs for each user
    print("Compute top 10 recs per user...")
    topNPredicted = RecommenderMetrics.GetTopN(allPredictions, n=10)

    # See how often we recommended a movie the user actually rated
    print("\nHit Rate: ", RecommenderMetrics.HitRate(topNPredicted, leftOutPredictions))

    # Break down hit rate by rating value
    print("\nrHR (Hit Rate by Rating value): ")
    RecommenderMetrics.RatingHitRate(topNPredicted, leftOutPredictions)

    # See how often we recommended a movie the user actually liked
    print("\ncHR (Cumulative Hit Rate, rating >= 4): ", RecommenderMetrics.CumulativeHitRate(topNPredicted, leftOutPredictions, 4.0))

    # Compute ARHR
    print("\nARHR (Average Reciprocal Hit Rank): ", RecommenderMetrics.AverageReciprocalHitRank(topNPredicted, leftOutPredictions))

print("\nComputing complete recommendations, no hold outs...")
algo.fit(fullTrainSet)
bigTestSet = fullTrainSet.build_anti_testset()
allPredictions = algo.test(bigTestSet)
topNPredicted = RecommenderMetrics.GetTopN(allPredictions, n=10)

# Print user coverage with a minimum predicted rating of 4.0:
print("\nUser coverage: ", RecommenderMetrics.UserCoverage(topNPredicted, fullTrainSet.n_users, ratingThreshold=4.0))

# Measure diversity of recommendations:
print("\nDiversity: ", RecommenderMetrics.Diversity(topNPredicted, simsAlgo))

# Measure novelty (average popularity rank of recommendations):
print("\nNovelty (average popularity rank): ", RecommenderMetrics.Novelty(topNPredicted, rankings))

Loading movie ratings...

Computing movie popularity ranks so we can measure novelty later...

Computing item similarities so we can measure diversity later...
Estimating biases using als...

In [1]:
14%5

4

In [1]:
крч нужно сделать рфм, но проблема рфма в том что она не предназанчена для покупателей,так что надо будет делать групбай айтемс

SyntaxError: invalid syntax (<ipython-input-1-1dfdf090e968>, line 1)